#!/usr/bin/env bash
#
# .devcontainer/update.sh — re-sync this repo from lootem/devcontainer, keeping
# whatever languages/tools/options are currently enabled.
#
# Manual only: this is NOT wired into any devcontainer lifecycle hook, so
# `curl|bash` never runs without you typing it yourself. Run it after an
# upstream change (e.g. a Dockerfile version bump) you want to pull in:
#
#   .devcontainer/update.sh
#   .devcontainer/update.sh --ref <sha>          # pin to a specific commit
#   .devcontainer/update.sh -- --force           # forward extra args to install.sh
#
# Note: this resets .devcontainer/Dockerfile's pinned tool versions to
# whatever <ref> currently pins upstream — that IS the update, since generated
# repos have no Renovate of their own to bump those pins independently.

set -euo pipefail

# The install.sh this script invokes below overwrites this very file (it's
# copied verbatim into every generated repo). Re-exec from a throwaway copy
# first, so bash isn't still reading this file off disk when that happens —
# otherwise the in-place rewrite can truncate the running script mid-read.
if [ -z "${UPDATE_SH_REEXECED:-}" ]; then
  ORIG_SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
  TMP_SELF="$(mktemp)"
  cp "$ORIG_SELF" "$TMP_SELF"
  chmod +x "$TMP_SELF"
  exec env UPDATE_SH_REEXECED=1 UPDATE_SH_ORIG="$ORIG_SELF" UPDATE_SH_TMP_SELF="$TMP_SELF" \
    bash "$TMP_SELF" "$@"
fi
trap 'rm -f "$UPDATE_SH_TMP_SELF"' EXIT

SCRIPT_DIR="$(cd "$(dirname "$UPDATE_SH_ORIG")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DOCKERFILE="$REPO_ROOT/.devcontainer/Dockerfile"
DEVCONTAINER_JSON="$REPO_ROOT/.devcontainer/devcontainer.json"

REF="main"
EXTRA_ARGS=()

die()  { echo "Error: $*" >&2; exit 1; }
info() { echo "[update] $*"; }

usage() {
  cat <<EOF
Usage: update.sh [--ref <ref>] [-- <extra install.sh args>]

Detects the languages/tools/skills/extensions currently enabled in this
repo's .devcontainer/, then re-runs install.sh from lootem/devcontainer
against them to pull in upstream changes.

      --ref <ref>   Branch/tag/commit to pull (default: $REF). Pin to a
                     commit sha for reproducibility (served at ltm.sh/dev/<ref>).
  -h, --help        Show this help

Anything after a lone "--" is forwarded verbatim to the fetched install.sh
(e.g. "-- --force" to overwrite files without prompting).

Run this from an interactive terminal: install.sh prompts before overwriting
files, and with no TTY those prompts default to "no" — so a non-interactive
run would skip the Dockerfile update entirely. Use "-- --force" if you must
run it unattended.
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --ref)     REF="$2"; shift 2 ;;
    --ref=*)   REF="${1#*=}"; shift ;;
    --)        shift; EXTRA_ARGS=("$@"); break ;;
    -h|--help) usage; exit 0 ;;
    *)         die "Unknown argument: $1 (see --help)" ;;
  esac
done

[ -f "$DOCKERFILE" ] \
  || die "No .devcontainer/Dockerfile found at $DOCKERFILE — run this from a repo generated by install.sh."

# Dockerfile ARG name → --language/--tool token. Must cover every ARG
# install.sh can flip, or a round-trip through update.sh silently drops that
# feature (see test.sh's token-set-coverage assertion in the source repo).
arg_token() {
  case "$1" in
    PYTHON)     echo "python" ;;
    GOLANG)     echo "go" ;;
    NODEJS)     echo "js" ;;
    DOTNET)     echo "dotnet" ;;
    AWSCLI)     echo "awscli" ;;
    AZCLI)      echo "azcli" ;;
    POWERSHELL) echo "pwsh" ;;
    AZPWSH)     echo "azpwsh" ;;
    *)          return 1 ;;
  esac
}

LANGS=()
TOOLS=()
while IFS= read -r arg_name; do
  [ -z "$arg_name" ] && continue
  # CLAUDECODE defaults to true and isn't a --language/--tool selector.
  [ "$arg_name" = "CLAUDECODE" ] && continue
  token="$(arg_token "$arg_name")" || continue
  case "$arg_name" in
    PYTHON|GOLANG|NODEJS|DOTNET) LANGS+=("$token") ;;
    *)                           TOOLS+=("$token") ;;
  esac
done < <(grep -oP '(?<=^ARG )[A-Z_]+(?==true)' "$DOCKERFILE")

ARGS=(--target "$REPO_ROOT")
[ ${#LANGS[@]} -gt 0 ] && ARGS+=(--language "$(IFS=,; echo "${LANGS[*]}")")
[ ${#TOOLS[@]} -gt 0 ] && ARGS+=(--tool "$(IFS=,; echo "${TOOLS[*]}")")

[ -d "$REPO_ROOT/.claude/skills" ] && ARGS+=(--skills)

if [ -f "$DEVCONTAINER_JSON" ] && command -v jq >/dev/null 2>&1 \
   && [ "$(jq -r '((.customizations.vscode.extensions // []) | length > 0)' "$DEVCONTAINER_JSON" 2>/dev/null)" = "true" ]; then
  ARGS+=(--extensions)
fi

ARGS+=("${EXTRA_ARGS[@]}")

info "Detected languages: ${LANGS[*]:-none}"
info "Detected tools: ${TOOLS[*]:-none}"
info "Re-running install.sh from lootem/devcontainer@$REF ..."

curl -fsSL "https://ltm.sh/dev/$REF" | bash -s -- "${ARGS[@]}"
